# Generated by Django 5.1.7 on 2025-03-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Mobile Development', 'Mobile Development'), ('Data Science', 'Data Science'), ('Machine Learning', 'Machine Learning'), ('Game Development', 'Game Development'), ('Graphic Design', 'Graphic Design'), ('Website Design', 'Website Design'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='projects',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
