# Generated by Django 4.2.10 on 2025-04-21 07:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projects_video_embed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='video_embed',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Paste the embed code from YouTube, Vimeo, or other video platforms. The code should start with <iframe>', null=True),
        ),
    ]
