# Generated by Django 4.2.10 on 2025-04-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_yourmodel_alter_projectphoto_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
