# Generated by Django 5.2 on 2025-04-23 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_delete_yourmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='image',
            new_name='main_image',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='thumbnail',
            new_name='thumbnail_image',
        ),
    ]
