# Generated by Django 5.2 on 2025-04-23 06:55

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_projects_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='technologies',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('python', 'Python'), ('django', 'Django'), ('react', 'React'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('sass', 'Sass'), ('bootstrap', 'Bootstrap'), ('postgresql', 'PostgreSQL'), ('sqlite', 'SQLite'), ('mysql', 'MySQL'), ('git', 'Git'), ('github', 'GitHub'), ('docker', 'Docker'), ('figma', 'Figma'), ('photoshop', 'Photoshop'), ('illustrator', 'Illustrator'), ('xd', 'Adobe XD'), ('premiere', 'Premiere'), ('aftereffects', 'After Effects')], max_length=149),
        ),
    ]
