# Generated by Django 5.2 on 2025-04-23 07:23

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_projects_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='technologies',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Languages', [('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('scss', 'Sass'), ('kotlin', 'Kotlin')]), ('Frameworks & Libraries', [('django', 'Django'), ('gsap', 'GSAP')]), ('Databases', [('sqlite', 'SQLite')]), ('Tools & IDEs', [('github', 'GitHub'), ('android_studio', 'Android Studio'), ('unity', 'Unity')]), ('Media', [('figma', 'Figma'), ('photoshop', 'Photoshop'), ('illustrator', 'Illustrator'), ('premiere', 'Premiere'), ('aftereffects', 'After Effects'), ('audition', 'Audition'), ('davinci', 'DaVinci Resolve')])], max_length=61),
        ),
    ]
