# Generated by Django 5.2 on 2025-04-23 08:10

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_projects_technologies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='video_embed',
        ),
        migrations.AlterField(
            model_name='projects',
            name='technologies',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Languages', [('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('kotlin', 'Kotlin')]), ('Frameworks & Libraries', [('scss', 'Scss'), ('django', 'Django'), ('gsap', 'GSAP')]), ('Databases', [('sqlite', 'SQLite')]), ('Tools & IDEs', [('github', 'GitHub'), ('android_studio', 'Android Studio'), ('unity', 'Unity')]), ('Media', [('figma', 'Figma'), ('photoshop', 'Photoshop'), ('illustrator', 'Illustrator'), ('premiere', 'Premiere'), ('aftereffects', 'After Effects'), ('audition', 'Audition'), ('davinci', 'DaVinci Resolve'), ('canva', 'Canva')])], max_length=255),
        ),
        migrations.CreateModel(
            name='ProjectEmbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed_code', models.TextField(help_text="Paste the full embed code (e.g., <iframe ...></iframe>) for a video or interactive media. One per entry. Example: <iframe width='560' height='315' src='https://www.youtube.com/embed/VIDEO_ID' frameborder='0' allowfullscreen></iframe>")),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeds', to='projects.projects')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
