# Generated by Django 5.2 on 2025-04-23 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_projects_video_embed_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectEmbed',
        ),
    ]
