# Generated by Django 5.2 on 2025-04-30 05:32

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_projects_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='technologies',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Languages', [('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('csharp', 'C#'), ('kotlin', 'Kotlin')]), ('Frameworks & Libraries', [('scss', 'Sass'), ('django', 'Django'), ('gsap', 'GSAP'), ('cloudinary', 'Cloudinary'), ('nodejs', 'Node.js'), ('imgur', 'Imgur')]), ('Development Tools', [('github', 'GitHub'), ('heroku', 'Heroku'), ('androidstudio', 'Android Studio'), ('cursor', 'Cursor')]), ('AI & Security Tools', [('chatgpt', 'ChatGPT'), ('claude', 'Claude'), ('autopsy', 'Autopsy'), ('cisco', 'Cisco'), ('tryhackme', 'TryHackMe')]), ('Design & Creative', [('figma', 'Figma'), ('photoshop', 'Photoshop'), ('illustrator', 'Illustrator'), ('lightroom', 'Lightroom'), ('canva', 'Canva')]), ('Video & Audio', [('premiere', 'Premiere Pro'), ('aftereffects', 'After Effects'), ('audition', 'Audition'), ('davinci', 'DaVinci Resolve')]), ('Game Development', [('unity', 'Unity'), ('twine', 'Twine'), ('harlow', 'Harlowe')])], max_length=255),
        ),
    ]
