# Generated by Django 5.2 on 2025-05-01 07:53

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_projectembed_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Mobile Development', 'Mobile Development'), ('Data Science', 'Data Science'), ('Machine Learning', 'Machine Learning'), ('Game Development', 'Game Development'), ('Graphic Design', 'Graphic Design'), ('Website Design', 'Website Design'), ('Application Development', 'Application Development'), ('Application Concept', 'Application Concept'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='projects',
            name='technologies',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Languages', [('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('csharp', 'C#'), ('kotlin', 'Kotlin')]), ('Frameworks & Libraries', [('scss', 'Sass'), ('django', 'Django'), ('gsap', 'GSAP'), ('cloudinary', 'Cloudinary'), ('nodejs', 'Node.js'), ('imgur', 'Imgur')]), ('Development Tools', [('github', 'GitHub'), ('heroku', 'Heroku'), ('androidstudio', 'Android Studio'), ('cursor', 'Cursor')]), ('AI & Security Tools', [('chatgpt', 'ChatGPT'), ('claude', 'Claude'), ('autopsy', 'Autopsy'), ('cisco', 'Cisco'), ('tryhackme', 'TryHackMe')]), ('Design & Creative', [('figma', 'Figma'), ('photoshop', 'Photoshop'), ('illustrator', 'Illustrator'), ('lightroom', 'Lightroom'), ('canva', 'Canva'), ('makeymakey', 'Makey Makey')]), ('Video & Audio', [('premiere', 'Premiere Pro'), ('aftereffects', 'After Effects'), ('audition', 'Audition'), ('davinci', 'DaVinci Resolve'), ('filmora', 'Wondershare Filmora')]), ('Game Development', [('unity', 'Unity'), ('twine', 'Twine'), ('harlowe', 'Harlowe'), ('bitsy', 'Bitsy')])], max_length=255),
        ),
    ]
