# Generated by Django 5.2 on 2025-05-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_alter_projects_category_alter_projects_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='featured',
            field=models.BooleanField(default=False, help_text='Show this project in the Featured Projects section.'),
        ),
    ]
